First assignments completed
MentoringProject/Assignments pull request #1
Opened 2023-11-19 18:43 UTC by SchruteFarmsCode

-metodę "divideByTwo", która przyjmie liczbę i zwróci ją podzieloną przez dwa
-metodę "divide", która przyjmie dwie liczby i zwróci wynik ich dzielenia
-metodę "checkLenght", która przyjmie tekst i zwróci jego długość
-używając powyżej metody napisz metodę "validateLenght", która przyjmie tekst i rzuci własnym wyjątkiem "TextTooLongException", dla tekstu dłuższego niż 10 znaków, lub wyjątkiem "TextTooShortException" dla tekstu krótszego od 4 znaków.
-metodę "reverse", która przyjmie tekst i zwróci tekst odwrócony (abc -> cba)
-metodę "checkAnagram", która przyjmie tekst i zwróci prawda lub fałsz w zależności od tego czy podany tekst jest anagramem
-metodę "checkPalindrome", która przyjmie dwa teksty i zwróci prawda lub fałsz w zależności czy oba wyrazy są swoimi palindromami
-metodę "factorial", która przyjmie liczbę i zwróci jej silnię
-metodę "fibonacci", która przyjmie liczbę n i zwróci n-tą liczbę ciągu liczb Fibonacciego

2023-11-24 17:44 UTC, pmat2 requested changes

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/Assignments.java
> +
remove empty line in method

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/Assignments.java
> +
empty line

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/Assignments.java
> +
empty line

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/Assignments.java
> +
empty lines

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/Assignments.java
> +    public  double divideByTwo(double num) {
add empty line before method

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/TextTooLongException.java
move this file to subpackage called 'exception'

2023-11-24 17:44 UTC, pmat2 commented on src/main/java/fundamentals/TextTooShortException.java
move this file to subpackage called 'exception'

2023-11-27 10:10 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/Assignments.java
> +
empty line removed

2023-11-27 10:10 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/Assignments.java
> +
empty line removed

2023-11-27 10:10 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/Assignments.java
> +
empty line removed

2023-11-27 10:10 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/Assignments.java
> +
empty line removed

2023-11-27 10:11 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/Assignments.java
> +    public  double divideByTwo(double num) {
added empty line before method

2023-11-27 10:12 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/TextTooLongException.java
moved this file to subpackage called 'exception'

2023-11-27 10:12 UTC, SchruteFarmsCode commented on src/main/java/fundamentals/TextTooShortException.java
moved this file to subpackage called 'exception'

2023-11-27 20:59 UTC, pmat2 approved these changes

2023-11-27 20:59 UTC, merged