second assignments completed
MentoringProject/Assignments pull request #3
Opened 2023-11-28 23:33 UTC by SchruteFarmsCode

2023-11-29 14:00 UTC, pmat2 requested changes

2023-11-29 14:00 UTC, pmat2 commented on src/main/java/Main.java
no need to change main

2023-11-29 14:00 UTC, pmat2 commented on src/main/java/fundamentals/exception/TextTooLongException.java
> -
cleaning up should not be addressed in this PR

2023-11-29 14:00 UTC, pmat2 commented on src/main/java/fundamentals/exception/TextTooShortException.java
> -
cleaning up should not be addressed in this PR

2023-11-29 19:26 UTC, pmat2 commented
> _ No description provided. _

Fill description

2023-12-15 23:29 UTC, SchruteFarmsCode commented on src/main/java/Main.java
corrected

2023-12-21 20:27 UTC, pmat2 requested changes

2023-12-21 20:27 UTC, pmat2 commented on src/main/java/fundamentals/MyStackImplementation.java
> +public class MyStackImplementation {
This needs to be generic

2023-12-21 20:27 UTC, pmat2 commented on src/main/java/fundamentals/MyStackImplementation.java
move to new package `collections`

2023-12-21 20:27 UTC, pmat2 commented on src/main/java/fundamentals/MyStackImplementation.java
Rename to MyStack

2023-12-28 11:05 UTC, pmat2 requested changes

2023-12-28 11:05 UTC, pmat2 commented on Assignments.iml
this should not be in remote repository

2023-12-28 11:05 UTC, pmat2 commented on src/main/java/Main.java
Not really 
![image](https://github.com/MentoringProject/Assignments/assets/46838259/1f452503-e920-403a-b173-f719cbd7f5d7)

2023-12-30 17:55 UTC, pmat2 approved these changes

2023-12-30 17:55 UTC, merged